name: Build and Release

on:
  push:
    tags:
      - 'master'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Added distribution
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: player-data-manipulator
        path: target/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: player-data-manipulator

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: player-data-manipulator/PlayerDataManipulator-v*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        files: player-data-manipulator/PlayerDataManipulator-v*.jar
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
